### PR TITLE
Update package versions

### PR DESCRIPTION
**Pull request by adam-fowler**

### CODE REVIEW

**Comment by adam-fowler** [comment]
@swift-server-bot test this please

**Comment by adam-fowler** [comment]
@swift-server-bot test install please

**Comment by patrickfreed** [comment]
@swift-server-bot add to allowlist

**Comment by patrickfreed** [comment]
Thanks for updating these, definitely a good idea to do so before the release.

Could you run `build_release.sh` script against this branch (just pass `update-package-versions` as the first argument) and verify that the output of `ldd swiftly` indicates no new system dependencies were introduced?

The existing release looks like the following:
```
$ ldd ~/.local/bin/swiftly
	linux-vdso.so.1 (0x00007ffc7dca9000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f44d1078000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f44d1055000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f44d1050000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f44d104a000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f44d0e68000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f44d0e4c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f44d0e2f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f44d0c3d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f44d49df000)
```

**Comment by adam-fowler** [comment]
The build_release script doesn't appear to be working. Fails `uname --machine`

**Comment by patrickfreed** [comment]
Hmm, I wonder if it needs to be run on Linux. It worked on my machine at least:
```
Step 10/10 : RUN ldd /swiftly
 ---> Running in f55ba0218265
	linux-vdso.so.1 (0x00007ffcae550000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f5807939000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f580771b000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f5807518000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f5807314000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f5806f92000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f5806d7d000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f5806b67000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f58067ba000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f580b610000)
```
Dependencies look the same. I filed https://github.com/swift-server/swiftly/issues/99 to track the work for automating this step.

**Pull request merged**
