### PR TITLE
Release updates

### PR DESCRIPTION
**Pull request by adam-fowler**

### CODE REVIEW

**Review by patrickfreed — APPROVED** [review]
thanks for making these updates, all look good to me.

did you try building with Swift 5.10? I don't foresee any issues but figured it'd be good to verify before publishing the binaries.

**Comment by patrickfreed** [comment]
Oh actually could you also update the test dockerfiles to use 5.10 now that our releases will be built with 5.10?

**Comment by patrickfreed** [comment]
Yeah everything else looks okay, just updating `test.dockerfile`. `test-ubi9.dockerfile`, and `test-amazonlinux2.dockerfile` to use 5.10 and having the test run is all that's left.

**Comment by adam-fowler** [comment]
@swift-server-bot test this please

**Comment by adam-fowler** [comment]
@swift-server-bot test this please

**Comment by adam-fowler** [comment]
@swift-server-bot test this please

**Comment by adam-fowler** [comment]
@swift-server-bot test this please

**Pull request merged**
