### PR TITLE
Installation script curl fail when the http request fails

### LINKED ISSUE #43: Installation script should detect when download failed
Right now, the installation script doesn't do a good job of detecting when a download fails. For example, the script will treat a 404 error response as if an executable was downloaded and only fail when actually trying to execute an HTML document. The script should be updated to adequately handle these cases and print a useful error message.

### PR DESCRIPTION
**Pull request by MahdiBM**
This PR adds the `--fail-with-body` flag to the curl command, which makes curl fail when the http request fails.
Also resolves #43.

To test, change `DOWNLOAD_URL`in the new script to an invalid url, then try the new script.

Example result of **before** this change:
```bash
~# . swiftly-install.sh 
This script will install swiftly, a Swift toolchain installer and manager.

swiftly data and configuration files directory: /root/.local/share/swiftly
swiftly executables installation directory: /usr/bin

Select one of the following:
1) Proceed with the installation (default)
2) Customize the installation paths
3) Cancel
> 1

Existing swiftly installation detected at /root/.local/share/swiftly, overwrite? (Y/n)
> y
Downloading swiftly from https://github.com/patrickfreed/swiftly/releases/latest/download/swiftly-x86_64-unknown-linux-gnu...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     31      0 --:--:-- --:--:-- --:--:--    31

swiftly executable written to /usr/bin/swiftly
swiftly data files written to /root/.local/share/swiftly
/usr/bin/swiftly: line 1: Not: command not found
```
And **after** this change:
```bash
~# . swiftly-install.sh 
This script will install swiftly, a Swift toolchain installer and manager.

swiftly data and configuration files directory: /root/.local/share/swiftly
swiftly executables installation directory: /usr/bin

Select one of the following:
1) Proceed with the installation (default)
2) Customize the installation paths
3) Cancel
> 1

Existing swiftly installation detected at /root/.local/share/swiftly, overwrite? (Y/n)
> y
Downloading swiftly from https://github.com/patrickfreed/swiftly/releases/latest/download/swiftly-x86_64-unknown-linux-gnu...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     25      0 --:--:-- --:--:-- --:--:--    25
curl: (22) The requested URL returned error: 404
```

(#44 was the original PR, but re-created the PR to see if the CI works on the PR now)

### CODE REVIEW

**Comment by adam-fowler** [comment]
@swift-server-bot test this please

**Comment by patrickfreed** [comment]
@swift-server-bot test install please

**Comment by yim-lee** [comment]
@swift-server-bot add to allowlist

**Comment by yim-lee** [comment]
@swift-server-bot test install please

**Comment by MahdiBM** [comment]
It seems that `--fail-with-body` is not supported in Ubuntu 18.04 & 20.04 like @patrickfreed was worried about:
```
Downloading swiftly from https://github.com/swift-server/swiftly/releases/latest/download/swiftly-x86_64-unknown-linux-gnu...
curl: option --fail-with-body: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```
I'll switch the flag to `--fail` when the CI run ends.

**Pull request merged**
