### PR TITLE
Installation script curl fail when the http request fails

### LINKED ISSUE #43: Installation script should detect when download failed
Right now, the installation script doesn't do a good job of detecting when a download fails. For example, the script will treat a 404 error response as if an executable was downloaded and only fail when actually trying to execute an HTML document. The script should be updated to adequately handle these cases and print a useful error message.

### PR DESCRIPTION
**Pull request by MahdiBM**
This PR adds the `--fail-with-body` flag to the curl command, which makes curl fail when the http request fails.
Also resolves #43.

To test, change `DOWNLOAD_URL`in the new script to an invalid url, then try the new script.

Example result of **before** this change:
```bash
~# . swiftly-install.sh 
This script will install swiftly, a Swift toolchain installer and manager.

swiftly data and configuration files directory: /root/.local/share/swiftly
swiftly executables installation directory: /usr/bin

Select one of the following:
1) Proceed with the installation (default)
2) Customize the installation paths
3) Cancel
> 1

Existing swiftly installation detected at /root/.local/share/swiftly, overwrite? (Y/n)
> y
Downloading swiftly from https://github.com/patrickfreed/swiftly/releases/latest/download/swiftly-x86_64-unknown-linux-gnu...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     31      0 --:--:-- --:--:-- --:--:--    31

swiftly executable written to /usr/bin/swiftly
swiftly data files written to /root/.local/share/swiftly
/usr/bin/swiftly: line 1: Not: command not found
```
And **after** this change:
```bash
~# . swiftly-install.sh 
This script will install swiftly, a Swift toolchain installer and manager.

swiftly data and configuration files directory: /root/.local/share/swiftly
swiftly executables installation directory: /usr/bin

Select one of the following:
1) Proceed with the installation (default)
2) Customize the installation paths
3) Cancel
> 1

Existing swiftly installation detected at /root/.local/share/swiftly, overwrite? (Y/n)
> y
Downloading swiftly from https://github.com/patrickfreed/swiftly/releases/latest/download/swiftly-x86_64-unknown-linux-gnu...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     25      0 --:--:-- --:--:-- --:--:--    25
curl: (22) The requested URL returned error: 404
```

### CODE REVIEW

**Comment by MahdiBM** [comment]
Now the PR also moves the curl "has_command" check to a later stage.

Users don't need to get stuck behind a "you don't have curl installed" message, if their platform isn't supported at all in the first place.

**Comment by patrickfreed** [comment]
Looks good, thanks for the PR! The `--fail-with-body` option was added in a (relatively) recent version of curl, so we might want to use the older `--fail` option instead. Let's wait until #35 is merged to see if this trips up our CI at all, and if not it's probably fine to just merge it as-is.

**Comment by MahdiBM** [comment]
ah that's a good point. After I already did this PR, while looking at some other scripts like rustup's, I noticed they use `--fail` instead of `--fail-with-body` and I was wondering why would they not want the body as some kind of extra info about the failure. This might explain that.

**Comment by MahdiBM** [comment]
Changed the `Swiftly` in the installation instructions to `swiftly` since you said that's intentional.

**Comment by patrickfreed** [comment]
@swift-server-bot please test install

**Comment by patrickfreed** [comment]
@swift-server-bot test install please

**Comment by patrickfreed** [comment]
@swift-server-bot test install please

**Comment by patrickfreed** [comment]
Hmm, could you reopen this PR? It doesn't look like CI is picking it up as is, probably because the PR was created before it was set up for this project.

**Comment by MahdiBM** [comment]
I thought i can close+reopen, but i'll just open a new PR to make sure the problem isn't affecting the PR and possibly save some time.

**Pull request closed without merging**
