### PR TITLE
feat: support fish shell in swiftly-install.sh (#72)

### LINKED ISSUE #72: Support fish shell in swiftly-install.sh
swiftly-install.sh is not currently compatible with the fish shell. We should update it to support it.

### PR DESCRIPTION
**Pull request by kkk669**
resolves #72

I added support for fish to `swiftly-install.sh`.

I added a unit test and confirm that all tests have passed by running `docker compose up install-test`. And of course, I tested that I could run `swiftly` after clean installation on my real environment.

### CODE REVIEW

**Comment by patrickfreed** [comment]
@swift-server-bot add to allowlist

**Comment by patrickfreed** [comment]
@swift-server-bot test install please

**Comment by patrickfreed** [comment]
Sorry for the slow turnaround on this, thank you for your contribution!

**Comment by kkk669** [comment]
Thank you for merging!

**Pull request merged**
